### ISSUE TITLE
test3

### ISSUE THREAD

**Issue by tqlblzj** [6Lackiu/EMplanner_Carla#2]
我在运行test3时明明contro是有输出的并且不为0，但是model3_actor.apply_control(control)不起作用，小车始终没有动，请教下这是为什么。肯定不是carla的原因因为我自己写的demo使用model3_actor.apply_control函数能控制小车运动

**Comment by 6Lackiu** [comment]
> 我在运行test3时明明contro是有输出的并且不为0，但是model3_actor.apply_control(control)不起作用，小车始终没有动，请教下这是为什么。肯定不是carla的原因因为我自己写的demo使用model3_actor.apply_control函数能控制小车运动

我没有遇到这种情况。请问输出信息是什么呢？

**Comment by tqlblzj** [comment]
> > 我在运行test3时明明contro是有输出的并且不为0，但是model3_actor.apply_control(control)不起作用，小车始终没有动，请教下这是为什么。肯定不是carla的原因因为我自己写的demo使用model3_actor.apply_control函数能控制小车运动
> 
> 我没有遇到这种情况。请问输出信息是什么呢？

刚解决了，把下面这几行注释即可
physics_control = carla.VehiclePhysicsControl()  # type: carla.VehiclePhysicsControl
physics_control.mass = 1412  # 质量kg
model3_actor.apply_physics_control(physics_control)
但是不懂原理是什么

**Comment by tqlblzj** [comment]
> > > 我在运行test3时明明contro是有输出的并且不为0，但是model3_actor.apply_control(control)不起作用，小车始终没有动，请教下这是为什么。肯定不是carla的原因因为我自己写的demo使用model3_actor.apply_control函数能控制小车运动
> > 
> > 
> > 我没有遇到这种情况。请问输出信息是什么呢？
> 
> 刚解决了，把下面这几行注释即可 physics_control = carla.VehiclePhysicsControl() # type: carla.VehiclePhysicsControl physics_control.mass = 1412 # 质量kg model3_actor.apply_physics_control(physics_control) 但是不懂原理是什么

我的环境是python3.8 Carla9.10

**Comment by 6Lackiu** [comment]
> > > > 我在运行test3时明明contro是有输出的并且不为0，但是model3_actor.apply_control(control)不起作用，小车始终没有动，请教下这是为什么。肯定不是carla的原因因为我自己写的demo使用model3_actor.apply_control函数能控制小车运动
> > > 
> > > 
> > > 我没有遇到这种情况。请问输出信息是什么呢？
> > 
> > 
> > 刚解决了，把下面这几行注释即可 physics_control = carla.VehiclePhysicsControl() # type: carla.VehiclePhysicsControl physics_control.mass = 1412 # 质量kg model3_actor.apply_physics_control(physics_control) 但是不懂原理是什么
> 
> 我的环境是python3.8 Carla9.10

我认为可能是由于carla版本不同，`apply_physics_control`后车辆模型的物理特性发生了改变，但是后续的control仍然基于之前的物理特性计算得出，导致控制失效。
不过这并不影响正常的规划与控制，可以继续使用。

**Comment by tqlblzj** [comment]
> > > > > 我在运行test3时明明contro是有输出的并且不为0，但是model3_actor.apply_control(control)不起作用，小车始终没有动，请教下这是为什么。肯定不是carla的原因因为我自己写的demo使用model3_actor.apply_control函数能控制小车运动
> > > > 
> > > > 
> > > > 我没有遇到这种情况。请问输出信息是什么呢？
> > > 
> > > 
> > > 刚解决了，把下面这几行注释即可 physics_control = carla.VehiclePhysicsControl() # type: carla.VehiclePhysicsControl physics_control.mass = 1412 # 质量kg model3_actor.apply_physics_control(physics_control) 但是不懂原理是什么
> > 
> > 
> > 我的环境是python3.8 Carla9.10
> 
> 我认为可能是由于carla版本不同，`apply_physics_control`后车辆模型的物理特性发生了改变，但是后续的control仍然基于之前的物理特性计算得出，导致控制失效。 不过这并不影响正常的规划与控制，可以继续使用。

但是我在运行test9时发现存在规划失败的情况，请问这是正常的么

**Comment by 6Lackiu** [comment]
@tqlblzj 
正常 因为程序还没有写完...
这只是一个demo，比较粗糙

**Comment by tqlblzj** [comment]
> @tqlblzj 正常 因为程序还没有写完... 这只是一个demo，比较粗糙

好的，最近刚开始学习路径规划，还是个小白，您的代码对我熟悉Carla以及学习路径规划非常有帮助，期待您的更新！

**Comment by 6Lackiu** [comment]
@tqlblzj 谢谢！共同进步！
