### ISSUE TITLE
fatal error 

### ISSUE THREAD

**Issue by szyvcdc** [6Lackiu/EMplanner_Carla#3]
当我运行test_9.py/test_3_1.py/simulation_4.py/simulation_2.py等文件时，一直出现fatal error错误，点击确认后UE4窗口崩溃关闭了，您知道是什么原因吗？

我的版本是
win11
carla0.9.12
python3.8.16

**Comment by 6Lackiu** [comment]
> 当我运行test_9.py/test_3_1.py/simulation_4.py/simulation_2.py等文件时，一直出现fatal error错误，点击确认后UE4窗口崩溃关闭了，您知道是什么原因吗？
> 
> 我的版本是 win11 carla0.9.12 python3.8.16

运行别的脚本会出现这种情况吗？
我没有遇到过您这种问题，也许[这篇博客](https://blog.csdn.net/anananajiushiwo/article/details/122936416)对您有效。

**Comment by szyvcdc** [comment]
好的，您发的连接我之前看到过，并没有解决，我运行examples里的py文件(manual control, automatic control, etc)没有报错，我需要再研究一下。
此外，我还有一个问题，您标记使用的的环境是：
carla0.9.12
python3.8
但是pythonapi\carla\dist路径下的carla-0.9.12-cp37.egg文件，应该是说0.9.12版本应该用py 3.7运行吧。

**Comment by 6Lackiu** [comment]
> 

您说的对，Python3.7确实是Carla0.9.12最稳定可靠的版本。
但这只代表了Carla0.9.12提供了Python 3.7的编译版本，并不意味着不能在其他版本的Python上运行0.9.12。

**Comment by 6Lackiu** [comment]
> 好的，您发的连接我之前看到过，并没有解决，我运行examples里的py文件(manual control, automatic control, etc)没有报错，我需要再研究一下。 此外，我还有一个问题，您标记使用的的环境是： carla0.9.12 python3.8 但是pythonapi\carla\dist路径下的carla-0.9.12-cp37.egg文件，应该是说0.9.12版本应该用py 3.7运行吧。

您说的对，Python 3.7确实是Carla 0.9.12最稳定可靠的版本。
但这只代表了Carla 0.9.12提供了Python 3.7的编译版本，并不意味着不能在其他版本的Python上运行0.9.12。

**Comment by szyvcdc** [comment]
感谢
